// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'infoWrap': string;
  'label': string;
  'labelWrap': string;
  'pictureWrap': string;
  'root': string;
  'statItem': string;
  'statValue': string;
  'statWrap': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
