// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  contentParallax: string;
  contentText: string;
  main: string;
  root: string;
  text: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
