// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropdown': string;
  'list': string;
  'open': string;
  'root': string;
  'target': string;
}
export const cssExports: CssExports;
export default cssExports;
