// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  logo: string;
  overlay: string;
  root: string;
  toggle: string;
  toggleMenu: string;
}
export const cssExports: CssExports;
export default cssExports;
