// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  link: string;
  linkActive: string;
  list: string;
  logo: string;
  nav: string;
  open: string;
}
export const cssExports: CssExports;
export default cssExports;
